### ISSUE TITLE
Can this method also perform well in downstream tasks of temporal classification?

### ISSUE THREAD

**Issue by hendredlorentz** [SaberaTalukder/TOTEM#1]
Can this method also perform well in downstream tasks of temporal classification?

**Comment by SaberaTalukder** [comment]
tl;dr: Yes! And the downstream classifier can be an MLP, Transformer, or other model architecture of your choosing.

Others (e.g. https://arxiv.org/pdf/2402.18546.pdf) have looked at TOTEM's within domain and zero shot classification capabilities extensively in the neuroscience domain.
